### ISSUE TITLE
Kobo Glo HD screen scaling issue

### ISSUE THREAD

**Issue by Riksu9000** [Kobo-InkBox/inkbox#29]
Sometimes the UI will only be a small portion of the screen. This seems to be a very common issue for me. The simplest way to get this issue is to just put the device to sleep and on wakeup, it will be like in the first photo. Upon navigating, it will be like the second photo. Restarting Inkbox fixes this issue. Upon closing the Reader file manager popup, the whole screen will refresh and return to the state in the first photo. Touch is still mapped to the full screen. The two small UIs aren't always perfectly identical.

<details><summary>Photos</summary>

![kobo1](https://user-images.githubusercontent.com/37774658/176095994-1633f093-1368-4502-99d2-bb73be665dae.jpg)
![kobo2](https://user-images.githubusercontent.com/37774658/176096026-8eb5a30c-cda2-4339-b076-a56147eae3ec.jpg)

</details>

**Comment by tux-linux** [comment]
Hello!
This has been fixed in upstream here: https://github.com/Kobo-InkBox/rootfs/blob/16e9d03a7d872cee8fadb5dabf3c96100b009349/etc/init.d/wake_standby.sh#L18-L31
It will be in version 2.0 of InkBox OS, expected to release soon™ with a truckload of improvements/overhauls/etc. The horrible "Recent books" section will also disappear, as well as the file manager, the two being replaced by something more touch-screen friendly and good design-wise.
Or you can integrate the fix yourself if you have some Linux experience.
Great to see another Glo HD running InkBox OS!

**Comment by Riksu9000** [comment]
Sounds exciting! I was about to open another issue about the Recent books screen going offscreen and garbled entries. I'll spare you with it if you think it won't be an issue with the new version.

<details><summary>Photo</summary>

![kobo3](https://user-images.githubusercontent.com/37774658/176100901-610f5bcb-30c6-48de-bff6-174ac1aedcb6.jpg)

</details>

**Comment by tux-linux** [comment]
A wrong thing with that bug is that it only happens sometimes. More often when the GUI is not started from a shell, but by the init script itself. Sometimes it displays them just fine (yes, that's Qt: plenty of bugs on already unstable hardware, yet probably one of the best GUI frameworks out there at the same time).
Did it happen everytime since you installed InkBox OS on your Glo HD?

**Comment by Szybet** [comment]
> A wrong thing with that bug is that it only happens sometimes. More often when the GUI is not started from a shell, but by the init script itself. Sometimes it displays them just fine (yes, that's Qt: plenty of bugs on already unstable hardware, yet probably one of the best GUI frameworks out there at the same time). Did it happen everytime since you installed InkBox OS on your Glo HD?

did you thinked about using kde qt version?
https://community.kde.org/Qt5PatchCollection
