### ISSUE TITLE
kobo nia install

### ISSUE THREAD

**Issue by espiritocz** [Kobo-InkBox/inkbox#42]
hi,
I guess I am still missing something..
once I plug the original kobo nia (n306) through usb to laptop, I can see /dev/sdc (~8 GB disk), but without partition.
I anyway tried xzcat inkbox-1.9-n306 through dd to this /dev/sdc, but then, after restart, the device forced factory reset.
Can you provide updated information on installing inkbox to Kobo Nia?
thank you

**Comment by Szybet** [comment]
Welcome
To make the issue resolve faster, i propose you join the discord or matrix server. i will later upload the solution here for everyone else

**Comment by Szybet** [comment]
The problem was that he dd the nickel book partition, for inkbox you need to flash the sd card

`not really! i appreciate and keep for later. now just using nickelmenu/koreader etc. along the offic. fw, for a while! that's still fun to me :D (koreader allows ssh transfers!!!) thanks/cheers/..!`
bruh
this can be closed @tux-linux 
~~also give me permissions at least for closing issues~~
